In [1]:
import re
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
url = "https://www.transfermarkt.com.br/premier-league/erfolge/wettbewerb/GB1"

headers = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:150.0) Gecko/20100101 Firefox/150.0"
}

response = requests.get(url, headers=headers)

response.status_code

200

In [3]:
soup = BeautifulSoup(response.content, "html.parser")

In [4]:
team_champSoup = soup.find_all('td', {'class':'hauptlink no-border-links'})
manager_champSoup = soup.find_all('td', {'class':'rechts'})

display(manager_champSoup)

[<td class="rechts"><a href="/mikel-arteta/profil/trainer/47620" id="47620" title="Mikel Arteta">Mikel Arteta</a></td>,
 <td class="rechts"><a href="/arne-slot/profil/trainer/34822" id="34822" title="Arne Slot">Arne Slot</a></td>,
 <td class="rechts"><a href="/pep-guardiola/profil/trainer/5672" id="5672" title="Pep Guardiola">Pep Guardiola</a></td>,
 <td class="rechts"><a href="/pep-guardiola/profil/trainer/5672" id="5672" title="Pep Guardiola">Pep Guardiola</a></td>,
 <td class="rechts"><a href="/pep-guardiola/profil/trainer/5672" id="5672" title="Pep Guardiola">Pep Guardiola</a></td>,
 <td class="rechts"><a href="/pep-guardiola/profil/trainer/5672" id="5672" title="Pep Guardiola">Pep Guardiola</a></td>,
 <td class="rechts"><a href="/jurgen-klopp/profil/trainer/118" id="118" title="Jürgen Klopp">Jürgen Klopp</a></td>,
 <td class="rechts"><a href="/pep-guardiola/profil/trainer/5672" id="5672" title="Pep Guardiola">Pep Guardiola</a></td>,
 <td class="rechts"><a href="/pep-guardiola/profil/trainer/5672" id="5672" title="Pep Guardiola">Pep Guardiola</a></td>,
 <td class="rechts"><a href="/antonio-conte/profil/trainer/3517" id="3517" title="Antonio Conte">Antonio Conte</a></td>,
 <td class="rechts"><a href="/claudio-ranieri/profil/trainer/456" id="456" title="Claudio Ranieri">Claudio Ranieri</a></td>,
 <td class="rechts"><a href="/jose-mourinho/profil/trainer/781" id="781" title="José Mourinho">José Mourinho</a></td>,
 <td class="rechts"><a href="/manuel-pellegrini/profil/trainer/1558" id="1558" title="Manuel Pellegrini">Manuel Pellegrini</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/roberto-mancini/profil/trainer/524" id="524" title="Roberto Mancini">Roberto Mancini</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/carlo-ancelotti/profil/trainer/523" id="523" title="Carlo Ancelotti">Carlo Ancelotti</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/jose-mourinho/profil/trainer/781" id="781" title="José Mourinho">José Mourinho</a></td>,
 <td class="rechts"><a href="/jose-mourinho/profil/trainer/781" id="781" title="José Mourinho">José Mourinho</a></td>,
 <td class="rechts"><a href="/arsene-wenger/profil/trainer/280" id="280" title="Arsène Wenger">Arsène Wenger</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/arsene-wenger/profil/trainer/280" id="280" title="Arsène Wenger">Arsène Wenger</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/arsene-wenger/profil/trainer/280" id="280" title="Arsène Wenger">Arsène Wenger</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/kenny-dalglish/profil/trainer/12320" id="12320" title="Kenny Dalglish">Kenny Dalglish</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/alex-ferguson/profil/trainer/4" id="4" title="Alex Ferguson">Alex Ferguson</a></td>,
 <td class="rechts"><a href="/howard-wilkinson/profil/trainer/1649" id="1649" title="Howard Wilkinson">Howard Wilkinson</a></td>,
 <td class="rechts"><a href="/george-graham/profil/trainer/2636" id="2636" title="George Graham">George Graham</a></td>,
 <td class="rechts"><a href="/kenny-dalglish/profil/trainer/12320" id="12320" title="Kenny Dalglish">Kenny Dalglish</a></td>,
 <td class="rechts"><a href="/george-graham/profil/trainer/2636" id="2636" title="George Graham">George Graham</a></td>,
 <td class="rechts"><a href="/kenny-dalglish/profil/trainer/12320" id="12320" title="Kenny Dalglish">Kenny Dalglish</a></td>,
 <td class="rechts"><a href="/howard-kendall/profil/trainer/6117" id="6117" title="Howard Kendall">Howard Kendall</a></td>,
 <td class="rechts"><a href="/kenny-dalglish/profil/trainer/12320" id="12320" title="Kenny Dalglish">Kenny Dalglish</a></td>,
 <td class="rechts"><a href="/howard-kendall/profil/trainer/6117" id="6117" title="Howard Kendall">Howard Kendall</a></td>,
 <td class="rechts"><a href="/joe-fagan/profil/trainer/21224" id="21224" title="Joe Fagan">Joe Fagan</a></td>,
 <td class="rechts"><a href="/bob-paisley/profil/trainer/17744" id="17744" title="Bob Paisley">Bob Paisley</a></td>,
 <td class="rechts"><a href="/bob-paisley/profil/trainer/17744" id="17744" title="Bob Paisley">Bob Paisley</a></td>,
 <td class="rechts"><a href="/ron-saunders/profil/trainer/27684" id="27684" title="Ron Saunders">Ron Saunders</a></td>,
 <td class="rechts"><a href="/bob-paisley/profil/trainer/17744" id="17744" title="Bob Paisley">Bob Paisley</a></td>,
 <td class="rechts"><a href="/bob-paisley/profil/trainer/17744" id="17744" title="Bob Paisley">Bob Paisley</a></td>,
 <td class="rechts"><a href="/brian-clough/profil/trainer/19548" id="19548" title="Brian Clough">Brian Clough</a></td>,
 <td class="rechts"><a href="/bob-paisley/profil/trainer/17744" id="17744" title="Bob Paisley">Bob Paisley</a></td>,
 <td class="rechts"><a href="/bob-paisley/profil/trainer/17744" id="17744" title="Bob Paisley">Bob Paisley</a></td>,
 <td class="rechts"><a href="/dave-mackay/profil/trainer/27313" id="27313" title="Dave Mackay">Dave Mackay</a></td>,
 <td class="rechts"><a href="/don-revie/profil/trainer/26716" id="26716" title="Don Revie">Don Revie</a></td>,
 <td class="rechts"><a href="/bill-shankly/profil/trainer/17742" id="17742" title="Bill Shankly">Bill Shankly</a></td>,
 <td class="rechts"><a href="/brian-clough/profil/trainer/19548" id="19548" title="Brian Clough">Brian Clough</a></td>,
 <td class="rechts"><a href="/bertie-mee/profil/trainer/28461" id="28461" title="Bertie Mee">Bertie Mee</a></td>,
 <td class="rechts"><a href="/harry-catterick/profil/trainer/27096" id="27096" title="Harry Catterick">Harry Catterick</a></td>,
 <td class="rechts"><a href="/don-revie/profil/trainer/26716" id="26716" title="Don Revie">Don Revie</a></td>,
 <td class="rechts"><a href="/joe-mercer/profil/trainer/26722" id="26722" title="Joe Mercer">Joe Mercer</a></td>,
 <td class="rechts"><a href="/sir-matt-busby/profil/trainer/16204" id="16204" title="Sir Matt Busby">Sir Matt Busby</a></td>,
 <td class="rechts"><a href="/bill-shankly/profil/trainer/17742" id="17742" title="Bill Shankly">Bill Shankly</a></td>,
 <td class="rechts"><a href="/sir-matt-busby/profil/trainer/16204" id="16204" title="Sir Matt Busby">Sir Matt Busby</a></td>,
 <td class="rechts"><a href="/bill-shankly/profil/trainer/17742" id="17742" title="Bill Shankly">Bill Shankly</a></td>,
 <td class="rechts"><a href="/harry-catterick/profil/trainer/27096" id="27096" title="Harry Catterick">Harry Catterick</a></td>,
 <td class="rechts"><a href="/sir-alf-ramsey/profil/trainer/20977" id="20977" title="Sir Alf Ramsey">Sir Alf Ramsey</a></td>,
 <td class="rechts"><a href="/bill-nicholson/profil/trainer/26064" id="26064" title="Bill Nicholson">Bill Nicholson</a></td>,
 <td class="rechts"><a href="/harry-potts/profil/trainer/32591" id="32591" title="Harry Potts">Harry Potts</a></td>,
 <td class="rechts"><a href="/stan-cullis/profil/trainer/32109" id="32109" title="Stan Cullis">Stan Cullis</a></td>,
 <td class="rechts"><a href="/stan-cullis/profil/trainer/32109" id="32109" title="Stan Cullis">Stan Cullis</a></td>,
 <td class="rechts"><a href="/sir-matt-busby/profil/trainer/16204" id="16204" title="Sir Matt Busby">Sir Matt Busby</a></td>,
 <td class="rechts"><a href="/sir-matt-busby/profil/trainer/16204" id="16204" title="Sir Matt Busby">Sir Matt Busby</a></td>,
 <td class="rechts"><a href="/ted-drake/profil/trainer/75650" id="75650" title="Ted Drake">Ted Drake</a></td>,
 <td class="rechts"><a href="/stan-cullis/profil/trainer/32109" id="32109" title="Stan Cullis">Stan Cullis</a></td>,
 <td class="rechts"><a href="/tom-whittaker/profil/trainer/34402" id="34402" title="Tom Whittaker">Tom Whittaker</a></td>,
 <td class="rechts"><a href="/sir-matt-busby/profil/trainer/16204" id="16204" title="Sir Matt Busby">Sir Matt Busby</a></td>,
 <td class="rechts"><a href="/arthur-rowe/profil/trainer/75635" id="75635" title="Arthur Rowe">Arthur Rowe</a></td>,
 <td class="rechts"><a href="/bob-jackson/profil/trainer/102514" id="102514" title="Bob Jackson">Bob Jackson</a></td>,
 <td class="rechts"><a href="/bob-jackson/profil/trainer/102514" id="102514" title="Bob Jackson">Bob Jackson</a></td>,
 <td class="rechts"><a href="/tom-whittaker/profil/trainer/34402" id="34402" title="Tom Whittaker">Tom Whittaker</a></td>,
 <td class="rechts"><a href="/george-kay/profil/trainer/39517" id="39517" title="George Kay">George Kay</a></td>,
 <td class="rechts"><a href="/theo-kelly/profil/trainer/75675" id="75675" title="Theo Kelly">Theo Kelly</a></td>,
 <td class="rechts"><a href="/george-allison/profil/trainer/75653" id="75653" title="George Allison">George Allison</a></td>,
 <td class="rechts"><a href="/wilf-wild/profil/trainer/75643" id="75643" title="Wilf Wild">Wilf Wild</a></td>,
 <td class="rechts"><a href="/john-cochrane/profil/trainer/124349" id="124349" title="John Cochrane">John Cochrane</a></td>,
 <td class="rechts"><a href="/george-allison/profil/trainer/75653" id="75653" title="George Allison">George Allison</a></td>,
 <td class="rechts"><a href="/joe-shaw/profil/trainer/75638" id="75638" title="Joe Shaw">Joe Shaw</a></td>,
 <td class="rechts"><a href="/herbert-chapman/profil/trainer/34395" id="34395" title="Herbert Chapman">Herbert Chapman</a></td>,
 <td class="rechts"><a href="/thomas-mcintosh/profil/trainer/75674" id="75674" title="Thomas McIntosh">Thomas McIntosh</a></td>,
 <td class="rechts"><a href="/herbert-chapman/profil/trainer/34395" id="34395" title="Herbert Chapman">Herbert Chapman</a></td>,
 <td class="rechts"><a href="/robert-brown/profil/trainer/124340" id="124340" title="Robert Brown">Robert Brown</a></td>,
 <td class="rechts"><a href="/robert-brown/profil/trainer/124340" id="124340" title="Robert Brown">Robert Brown</a></td>,
 <td class="rechts"><a href="/thomas-mcintosh/profil/trainer/75674" id="75674" title="Thomas McIntosh">Thomas McIntosh</a></td>,
 <td class="rechts"><a href="/frank-watt/profil/trainer/93888" id="93888" title="Frank Watt">Frank Watt</a></td>,
 <td class="rechts"><a href="/cecil-potter/profil/trainer/126823" id="126823" title="Cecil Potter">Cecil Potter</a></td>,
 <td class="rechts"><a href="/herbert-chapman/profil/trainer/34395" id="34395" title="Herbert Chapman">Herbert Chapman</a></td>,
 <td class="rechts"><a href="/herbert-chapman/profil/trainer/34395" id="34395" title="Herbert Chapman">Herbert Chapman</a></td>,
 <td class="rechts"><a href="/matt-mcqueen/profil/trainer/39519" id="39519" title="Matt McQueen">Matt McQueen</a></td>,
 <td class="rechts"><a href="/david-ashworth/profil/trainer/39520" id="39520" title="David Ashworth">David Ashworth</a></td>,
 <td class="rechts"><a href="/john-haworth/profil/trainer/126841" id="126841" title="John Haworth">John Haworth</a></td>,
 <td class="rechts"><a href="/fred-everiss/profil/trainer/115308" id="115308" title="Fred Everiss">Fred Everiss</a></td>,
 <td class="rechts"><a href="/will-cuff/profil/trainer/75668" id="75668" title="Will Cuff">Will Cuff</a></td>,
 <td class="rechts"><a href="/robert-middleton/profil/trainer/126844" id="126844" title="Robert Middleton">Robert Middleton</a></td>,
 <td class="rechts"><a href="/bob-kyle/profil/trainer/128287" id="128287" title="Bob Kyle">Bob Kyle</a></td>,
 <td class="rechts"><a href="/robert-middleton/profil/trainer/126844" id="126844" title="Robert Middleton">Robert Middleton</a></td>,
 <td class="rechts"><a href="/ernest-mangnall/profil/trainer/75640" id="75640" title="Ernest Mangnall">Ernest Mangnall</a></td>,
 <td class="rechts"></td>,
 <td class="rechts"><a href="/frank-watt/profil/trainer/93888" id="93888" title="Frank Watt">Frank Watt</a></td>,
 <td class="rechts"><a href="/ernest-mangnall/profil/trainer/75640" id="75640" title="Ernest Mangnall">Ernest Mangnall</a></td>,
 <td class="rechts"><a href="/frank-watt/profil/trainer/93888" id="93888" title="Frank Watt">Frank Watt</a></td>,
 <td class="rechts"><a href="/tom-watson/profil/trainer/39521" id="39521" title="Tom Watson">Tom Watson</a></td>,
 <td class="rechts"><a href="/frank-watt/profil/trainer/93888" id="93888" title="Frank Watt">Frank Watt</a></td>,
 <td class="rechts"></td>,
 <td class="rechts"></td>,
 <td class="rechts"></td>,
 <td class="rechts"><a href="/tom-watson/profil/trainer/39521" id="39521" title="Tom Watson">Tom Watson</a></td>,
 <td class="rechts"></td>,
 <td class="rechts"></td>,
 <td class="rechts"></td>,
 <td class="rechts"></td>,
 <td class="rechts"></td>,
 <td class="rechts"><a href="/tom-watson/profil/trainer/39521" id="39521" title="Tom Watson">Tom Watson</a></td>,
 <td class="rechts"></td>,
 <td class="rechts"><a href="/tom-watson/profil/trainer/39521" id="39521" title="Tom Watson">Tom Watson</a></td>,
 <td class="rechts"><a href="/tom-watson/profil/trainer/39521" id="39521" title="Tom Watson">Tom Watson</a></td>,
 <td class="rechts"><a href="/dick-molyneux/profil/trainer/75667" id="75667" title="Dick Molyneux">Dick Molyneux</a></td>,
 <td class="rechts"></td>,
 <td class="rechts"></td>]

In [5]:
team_champSoup[0].string
team_champSoup[0].find('a').get('href')

'/fc-arsenal/startseite/verein/11/saison_id/2025'

In [6]:
team_champ = []
clock = 0

for row in team_champSoup:
    if clock == 20: break # last 20 years
    temp = []
    temp.append(row.find('a').get('href'))
    temp.append(row.string)
    team_champ.append(temp)
    clock += 1

df_team_champ = pd.DataFrame(team_champ)

display(df_team_champ)

                                                    0                     1
0     /fc-arsenal/startseite/verein/11/saison_id/2025            FC Arsenal
1   /fc-liverpool/startseite/verein/31/saison_id/2024          FC Liverpool
2   /manchester-city/startseite/verein/281/saison_...    Manchester City FC
3   /manchester-city/startseite/verein/281/saison_...    Manchester City FC
4   /manchester-city/startseite/verein/281/saison_...    Manchester City FC
5   /manchester-city/startseite/verein/281/saison_...    Manchester City FC
6   /fc-liverpool/startseite/verein/31/saison_id/2019          FC Liverpool
7   /manchester-city/startseite/verein/281/saison_...    Manchester City FC
8   /manchester-city/startseite/verein/281/saison_...    Manchester City FC
9    /fc-chelsea/startseite/verein/631/saison_id/2016            Chelsea FC
10  /leicester-city/startseite/verein/1003/saison_...     Leicester City FC
11   /fc-chelsea/startseite/verein/631/saison_id/2014            Chelsea FC
12  /manchester-city/startseite/verein/281/saison_...    Manchester City FC
13  /manchester-united/startseite/verein/985/saiso...  Manchester United FC
14  /manchester-city/startseite/verein/281/saison_...    Manchester City FC
15  /manchester-united/startseite/verein/985/saiso...  Manchester United FC
16   /fc-chelsea/startseite/verein/631/saison_id/2009            Chelsea FC
17  /manchester-united/startseite/verein/985/saiso...  Manchester United FC
18  /manchester-united/startseite/verein/985/saiso...  Manchester United FC
19  /manchester-united/startseite/verein/985/saiso...  Manchester United FC

In [7]:
manager_champSoup[0].string
manager_champSoup[0].find('a').get('id')

'47620'

In [8]:
manager_champ = []
clock = 0

for row in manager_champSoup:
    if clock == 20: break # last 20 years
    temp = []
    temp.append(row.find('a').get('href'))
    temp.append(row.find('a').get('id'))
    temp.append(row.string)
    manager_champ.append(temp)
    clock += 1

df_manager_champ = pd.DataFrame(manager_champ)

display(df_manager_champ)

                                         0      1                  2
0       /mikel-arteta/profil/trainer/47620  47620       Mikel Arteta
1          /arne-slot/profil/trainer/34822  34822          Arne Slot
2       /pep-guardiola/profil/trainer/5672   5672      Pep Guardiola
3       /pep-guardiola/profil/trainer/5672   5672      Pep Guardiola
4       /pep-guardiola/profil/trainer/5672   5672      Pep Guardiola
5       /pep-guardiola/profil/trainer/5672   5672      Pep Guardiola
6         /jurgen-klopp/profil/trainer/118    118       Jürgen Klopp
7       /pep-guardiola/profil/trainer/5672   5672      Pep Guardiola
8       /pep-guardiola/profil/trainer/5672   5672      Pep Guardiola
9       /antonio-conte/profil/trainer/3517   3517      Antonio Conte
10     /claudio-ranieri/profil/trainer/456    456    Claudio Ranieri
11       /jose-mourinho/profil/trainer/781    781      José Mourinho
12  /manuel-pellegrini/profil/trainer/1558   1558  Manuel Pellegrini
13         /alex-ferguson/profil/trainer/4      4      Alex Ferguson
14     /roberto-mancini/profil/trainer/524    524    Roberto Mancini
15         /alex-ferguson/profil/trainer/4      4      Alex Ferguson
16     /carlo-ancelotti/profil/trainer/523    523    Carlo Ancelotti
17         /alex-ferguson/profil/trainer/4      4      Alex Ferguson
18         /alex-ferguson/profil/trainer/4      4      Alex Ferguson
19         /alex-ferguson/profil/trainer/4      4      Alex Ferguson

In [9]:
df_champions = pd.concat([df_team_champ,df_manager_champ], axis=1)
df_champions.columns = ['season_link', 'team_name', 'manager_link', 'manager_id', 'manager_name']
display(df_champions)

,season_link,team_name,manager_link,manager_id,manager_name
0,/fc-arsenal/startseite/verein/11/saison_id/2025,FC Arsenal,/mikel-arteta/profil/trainer/47620,47620,Mikel Arteta
1,/fc-liverpool/startseite/verein/31/saison_id/2024,FC Liverpool,/arne-slot/profil/trainer/34822,34822,Arne Slot
2,/manchester-city/startseite/verein/281/saison_...,Manchester City FC,/pep-guardiola/profil/trainer/5672,5672,Pep Guardiola
3,/manchester-city/startseite/verein/281/saison_...,Manchester City FC,/pep-guardiola/profil/trainer/5672,5672,Pep Guardiola
4,/manchester-city/startseite/verein/281/saison_...,Manchester City FC,/pep-guardiola/profil/trainer/5672,5672,Pep Guardiola
5,/manchester-city/startseite/verein/281/saison_...,Manchester City FC,/pep-guardiola/profil/trainer/5672,5672,Pep Guardiola
6,/fc-liverpool/startseite/verein/31/saison_id/2019,FC Liverpool,/jurgen-klopp/profil/trainer/118,118,Jürgen Klopp
7,/manchester-city/startseite/verein/281/saison_...,Manchester City FC,/pep-guardiola/profil/trainer/5672,5672,Pep Guardiola
8,/manchester-city/startseite/verein/281/saison_...,Manchester City FC,/pep-guardiola/profil/trainer/5672,5672,Pep Guardiola
9,/fc-chelsea/startseite/verein/631/saison_id/2016,Chelsea FC,/antonio-conte/profil/trainer/3517,3517,Antonio Conte
10,/leicester-city/startseite/verein/1003/saison_...,Leicester City FC,/claudio-ranieri/profil/trainer/456,456,Claudio Ranieri
11,/fc-chelsea/startseite/verein/631/saison_id/2014,Chelsea FC,/jose-mourinho/profil/trainer/781,781,José Mourinho
12,/manchester-city/startseite/verein/281/saison_...,Manchester City FC,/manuel-pellegrini/profil/trainer/1558,1558,Manuel Pellegrini
13,/manchester-united/startseite/verein/985/saiso...,Manchester United FC,/alex-ferguson/profil/trainer/4,4,Alex Ferguson
14,/manchester-city/startseite/verein/281/saison_...,Manchester City FC,/roberto-mancini/profil/trainer/524,524,Roberto Mancini
15,/manchester-united/startseite/verein/985/saiso...,Manchester United FC,/alex-ferguson/profil/trainer/4,4,Alex Ferguson
16,/fc-chelsea/startseite/verein/631/saison_id/2009,Chelsea FC,/carlo-ancelotti/profil/trainer/523,523,Carlo Ancelotti
17,/manchester-united/startseite/verein/985/saiso...,Manchester United FC,/alex-ferguson/profil/trainer/4,4,Alex Ferguson
18,/manchester-united/startseite/verein/985/saiso...,Manchester United FC,/alex-ferguson/profil/trainer/4,4,Alex Ferguson
19,/manchester-united/startseite/verein/985/saiso...,Manchester United FC,/alex-ferguson/profil/trainer/4,4,Alex Ferguson