In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
headers = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:150.0) Gecko/20100101 Firefox/150.0"
    }

In [3]:
url = 'https://www.transfermarkt.com.br/premier-league/spieltagtabelle/wettbewerb/GB1/saison_id/2025/spieltag/27'
response = requests.get(url,headers=headers)
soup = BeautifulSoup(response.content,'html.parser')

In [4]:
info = soup.find_all('tbody')
table_info = info[2].find_all('tr')

In [5]:
round_classification = []

for row in table_info:
    temp = []

    placement = row.find('td',{'class':'rechts hauptlink'}).get_text().strip()
    team = row.find('a').get('title')

    temp.append(placement)
    temp.append(team)

    adicional_info = row.find_all('td', {'class':'zentriert'})

    for i, item in enumerate(adicional_info):
        if i == 0: continue
        temp.append(item.string)

    round_classification.append(temp)

df_round_classification = pd.DataFrame(round_classification)
df_round_classification.columns = ['placement','team_name','matches','wins','draws','losses','goals','goal_dif','points']
display(df_round_classification)

,placement,team_name,matches,wins,draws,losses,goals,goal_dif,points
0,1,FC Arsenal,27,18,6,3,54:19,35,60
1,2,Manchester City FC,27,17,5,5,56:25,31,56
2,3,Aston Villa FC,27,15,6,6,38:28,10,51
3,4,Manchester United FC,27,13,9,5,48:37,11,48
4,5,Chelsea FC,27,12,9,6,48:31,17,45
5,6,FC Liverpool,27,13,6,8,42:35,7,45
6,7,Brentford FC,27,12,4,11,40:37,3,40
7,8,AFC Bournemouth,27,9,11,7,43:45,-2,38
8,9,FC Everton,27,10,7,10,29:31,-2,37
9,10,FC Fulham,27,11,4,12,38:41,-3,37
10,11,Newcastle United,27,10,6,11,38:39,-1,36
11,12,AFC Sunderland,27,9,9,9,28:33,-5,36
12,13,Crystal Palace FC,27,9,8,10,29:32,-3,35
13,14,Brighton & Hove Albion,27,8,10,9,36:34,2,34
14,15,Leeds United FC,27,7,10,10,37:46,-9,31
15,16,Tottenham Hotspur,27,7,8,12,37:41,-4,29
16,17,Nottingham Forest,27,7,6,14,25:39,-14,27
17,18,West Ham United,27,6,7,14,32:49,-17,25
18,19,FC Burnley,27,4,7,16,29:52,-23,19
19,20,Wolverhampton Wanderers,27,1,6,20,16:49,-33,9

In [6]:
round_classification = []

for n_round in range(1,39):
    url = f'https://www.transfermarkt.com.br/premier-league/spieltagtabelle/wettbewerb/GB1/saison_id/2025/spieltag/{n_round}'
    response = requests.get(url,headers=headers)
    soup = BeautifulSoup(response.content,'html.parser')

    info = soup.find_all('tbody')
    table_info = info[2].find_all('tr')


    for row in table_info:
        temp = []

        season_key = 'PL-2025'
        if n_round < 10: round_key = 'R-2025-0' + str(n_round)
        else: round_key = 'R-2025-' + str(n_round)
        
        temp.append(season_key)
        temp.append(round_key)

        placement = row.find('td',{'class':'rechts hauptlink'}).get_text().strip()
        team = row.find('a').get('title')

        temp.append(placement)
        temp.append(team)

        adicional_info = row.find_all('td', {'class':'zentriert'})

        for i, item in enumerate(adicional_info):
            if i == 0: continue
            temp.append(item.string)

        round_classification.append(temp)

df_round_classification = pd.DataFrame(round_classification)
df_round_classification.columns = ['season_id','round_id','placement','team_name','matches','wins','draws','losses','goals','goal_dif','points']
display(df_round_classification.head(60))
display(len(round_classification))

,season_id,round_id,placement,team_name,matches,wins,draws,losses,goals,goal_dif,points
0,PL-2025,R-2025-01,1,Manchester City FC,1,1,0,0,4:0,4,3
1,PL-2025,R-2025-01,2,AFC Sunderland,1,1,0,0,3:0,3,3
2,PL-2025,R-2025-01,2,Tottenham Hotspur,1,1,0,0,3:0,3,3
3,PL-2025,R-2025-01,4,FC Liverpool,1,1,0,0,4:2,2,3
4,PL-2025,R-2025-01,5,Nottingham Forest,1,1,0,0,3:1,2,3
5,PL-2025,R-2025-01,6,FC Arsenal,1,1,0,0,1:0,1,3
6,PL-2025,R-2025-01,6,Leeds United FC,1,1,0,0,1:0,1,3
7,PL-2025,R-2025-01,8,Brighton & Hove Albion,1,0,1,0,1:1,0,1
8,PL-2025,R-2025-01,8,FC Fulham,1,0,1,0,1:1,0,1
9,PL-2025,R-2025-01,10,Aston Villa FC,1,0,1,0,0:0,0,1
10,PL-2025,R-2025-01,10,Chelsea FC,1,0,1,0,0:0,0,1
11,PL-2025,R-2025-01,10,Crystal Palace FC,1,0,1,0,0:0,0,1
12,PL-2025,R-2025-01,10,Newcastle United,1,0,1,0,0:0,0,1
13,PL-2025,R-2025-01,14,FC Everton,1,0,0,1,0:1,-1,0
14,PL-2025,R-2025-01,14,Manchester United FC,1,0,0,1,0:1,-1,0
15,PL-2025,R-2025-01,16,AFC Bournemouth,1,0,0,1,2:4,-2,0
16,PL-2025,R-2025-01,17,Brentford FC,1,0,0,1,1:3,-2,0
17,PL-2025,R-2025-01,18,FC Burnley,1,0,0,1,0:3,-3,0
18,PL-2025,R-2025-01,18,West Ham United,1,0,0,1,0:3,-3,0
19,PL-2025,R-2025-01,20,Wolverhampton Wanderers,1,0,0,1,0:4,-4,0
20,PL-2025,R-2025-02,1,FC Arsenal,2,2,0,0,6:0,6,6
21,PL-2025,R-2025-02,2,Tottenham Hotspur,2,2,0,0,5:0,5,6
22,PL-2025,R-2025-02,3,FC Liverpool,2,2,0,0,7:4,3,6
23,PL-2025,R-2025-02,4,Chelsea FC,2,1,1,0,5:1,4,4
24,PL-2025,R-2025-02,5,Nottingham Forest,2,1,1,0,4:2,2,4
25,PL-2025,R-2025-02,6,Manchester City FC,2,1,0,1,4:2,2,3
26,PL-2025,R-2025-02,7,AFC Sunderland,2,1,0,1,3:2,1,3
27,PL-2025,R-2025-02,8,FC Everton,2,1,0,1,2:1,1,3
28,PL-2025,R-2025-02,9,AFC Bournemouth,2,1,0,1,3:4,-1,3
29,PL-2025,R-2025-02,10,Brentford FC,2,1,0,1,2:3,-1,3
30,PL-2025,R-2025-02,10,FC Burnley,2,1,0,1,2:3,-1,3
31,PL-2025,R-2025-02,12,Leeds United FC,2,1,0,1,1:5,-4,3
32,PL-2025,R-2025-02,13,FC Fulham,2,0,2,0,2:2,0,2
33,PL-2025,R-2025-02,14,Crystal Palace FC,2,0,2,0,1:1,0,2
34,PL-2025,R-2025-02,15,Newcastle United,2,0,1,1,2:3,-1,1
35,PL-2025,R-2025-02,16,Manchester United FC,2,0,1,1,1:2,-1,1
36,PL-2025,R-2025-02,17,Aston Villa FC,2,0,1,1,0:1,-1,1
37,PL-2025,R-2025-02,18,Brighton & Hove Albion,2,0,1,1,1:3,-2,1
38,PL-2025,R-2025-02,19,Wolverhampton Wanderers,2,0,0,2,0:5,-5,0
39,PL-2025,R-2025-02,20,West Ham United,2,0,0,2,1:8,-7,0
40,PL-2025,R-2025-03,1,FC Liverpool,3,3,0,0,8:4,4,9
41,PL-2025,R-2025-03,2,Chelsea FC,3,2,1,0,7:1,6,7
42,PL-2025,R-2025-03,3,FC Arsenal,3,2,0,1,6:1,5,6
43,PL-2025,R-2025-03,4,Tottenham Hotspur,3,2,0,1,5:1,4,6
44,PL-2025,R-2025-03,5,FC Everton,3,2,0,1,5:3,2,6
45,PL-2025,R-2025-03,5,AFC Sunderland,3,2,0,1,5:3,2,6
46,PL-2025,R-2025-03,7,AFC Bournemouth,3,2,0,1,4:4,0,6
47,PL-2025,R-2025-03,8,Crystal Palace FC,3,1,2,0,4:1,3,5
48,PL-2025,R-2025-03,9,Manchester United FC,3,1,1,1,4:4,0,4
49,PL-2025,R-2025-03,10,Nottingham Forest,3,1,1,1,4:5,-1,4
50,PL-2025,R-2025-03,11,Brighton & Hove Albion,3,1,1,1,3:4,-1,4
51,PL-2025,R-2025-03,12,Leeds United FC,3,1,1,1,1:5,-4,4
52,PL-2025,R-2025-03,13,Manchester City FC,3,1,0,2,5:4,1,3
53,PL-2025,R-2025-03,14,FC Burnley,3,1,0,2,4:6,-2,3
54,PL-2025,R-2025-03,15,Brentford FC,3,1,0,2,3:5,-2,3
55,PL-2025,R-2025-03,16,West Ham United,3,1,0,2,4:8,-4,3
56,PL-2025,R-2025-03,17,Newcastle United,3,0,2,1,2:3,-1,2
57,PL-2025,R-2025-03,18,FC Fulham,3,0,2,1,2:4,-2,2
58,PL-2025,R-2025-03,19,Aston Villa FC,3,0,1,2,0:4,-4,1
59,PL-2025,R-2025-03,20,Wolverhampton Wanderers,3,0,0,3,2:8,-6,0

760