**Countries to fix**
- Bosnia-Herzegovina;
- Congo;
- Cote d'Ivoire;
- Curacao;
- Czech Republic;
- Korea, South;
- St. Kitts & Nevis;
- The Gambia;
- Türkiye

**Right Countries**
- Bosnia and Herzegovina;
- Republic of the Congo;
- Côte d'Ivoire;
- Curaçao;
- Czechia;
- South Korea;
- Saint Kitts and Nevis;
- Gambia;
- Turkey

**Teams to fix**
- Brighton & Hove Albion
- Oldham Athletic

**Create**
- team_id
- country_id
- season dimension
- premier logo if team_name == for 2 clubs

# Data Modeling

In [1]:
import pandas as pd
import numpy as np

In [2]:
to_be_fixed = pd.read_csv(r'..\data-csv\premier-top-scorers.csv')

display(to_be_fixed)

,season_id,pos,country,age,player_name,team,matches,goals
0,GB1-1992,1,England,27,Teddy Sheringham,for 2 clubs,41,22
1,GB1-1992,2,England,26,Les Ferdinand,Queens Park Rangers,37,20
2,GB1-1992,3,England,24,Dean Holdsworth,Wimbledon FC (- 2004),36,19
3,GB1-1992,4,England,31,Micky Quinn,Coventry City,26,17
4,GB1-1992,5,England,25,David White,Manchester City,42,16
...,...,...,...,...,...,...,...,...
8920,GB1-2025,276,Denmark,25,Matt O'Riley,Brighton & Hove Albion,6,1
8921,GB1-2025,277,Portugal,23,Fábio Carvalho,Brentford FC,6,1
8922,GB1-2025,278,Italy,25,Lorenzo Lucca,Nottingham Forest,4,1
8923,GB1-2025,279,Wales,32,Ben Davies,Tottenham Hotspur,3,1
8924,GB1-2025,280,England,20,Tom Edozie,Wolverhampton Wanderers,3,1

In [3]:
right = "Bosnia and Herzegovina;Republic of the Congo;Côte d'Ivoire;Curaçao;Czechia;South Korea;Saint Kitts and Nevis;Gambia;Turkey"
wrong = "Bosnia-Herzegovina;Congo;Cote d'Ivoire;Curacao;Czech Republic;Korea, South;St. Kitts & Nevis;The Gambia;Türkiye"

right_list = right.split(';')
wrong_list = wrong.split(';')

new_df = to_be_fixed.copy()
for i, row in enumerate(wrong_list):
    new_df.replace(wrong_list[i],right_list[i],inplace=True)

display(new_df)

,season_id,pos,country,age,player_name,team,matches,goals
0,GB1-1992,1,England,27,Teddy Sheringham,for 2 clubs,41,22
1,GB1-1992,2,England,26,Les Ferdinand,Queens Park Rangers,37,20
2,GB1-1992,3,England,24,Dean Holdsworth,Wimbledon FC (- 2004),36,19
3,GB1-1992,4,England,31,Micky Quinn,Coventry City,26,17
4,GB1-1992,5,England,25,David White,Manchester City,42,16
...,...,...,...,...,...,...,...,...
8920,GB1-2025,276,Denmark,25,Matt O'Riley,Brighton & Hove Albion,6,1
8921,GB1-2025,277,Portugal,23,Fábio Carvalho,Brentford FC,6,1
8922,GB1-2025,278,Italy,25,Lorenzo Lucca,Nottingham Forest,4,1
8923,GB1-2025,279,Wales,32,Ben Davies,Tottenham Hotspur,3,1
8924,GB1-2025,280,England,20,Tom Edozie,Wolverhampton Wanderers,3,1

### Fact
- f_events
- f_topscorers
- f_placements

### Dimensions
- d_countries
- d_matches
- d_teams
- d_titles
- d_squads

In [4]:
# f_events
# f_topscorers
# f_placements

# d_countries
# d_matches
# d_teams
# d_titles
# d_squads

In [27]:
d_teams = pd.read_csv(r'..\data-csv\premier-logos.csv', sep=';')
d_teams.sort_values(['team_name'],ignore_index=True, inplace=True)
d_teams['team_id'] = d_teams.index + 101

display(d_teams)

,team_name,svg_link,team_id
0,AFC Bournemouth,https://upload.wikimedia.org/wikipedia/en/e/e5...,101
1,Arsenal FC,https://upload.wikimedia.org/wikipedia/en/5/53...,102
2,Aston Villa,https://upload.wikimedia.org/wikipedia/en/9/9a...,103
3,Barnsley FC,https://upload.wikimedia.org/wikipedia/en/c/c9...,104
4,Birmingham City,https://upload.wikimedia.org/wikipedia/en/6/68...,105
5,Blackburn Rovers,https://upload.wikimedia.org/wikipedia/en/0/0f...,106
6,Blackpool FC,https://upload.wikimedia.org/wikipedia/en/d/df...,107
7,Bolton Wanderers,https://upload.wikimedia.org/wikipedia/en/8/82...,108
8,Bradford City,https://upload.wikimedia.org/wikipedia/en/0/04...,109
9,Brentford FC,https://upload.wikimedia.org/wikipedia/en/2/2a...,110
10,Brighton & Hove Albion,https://upload.wikimedia.org/wikipedia/en/d/d0...,111
11,Burnley FC,https://upload.wikimedia.org/wikipedia/en/6/6d...,112
12,Cardiff City,https://upload.wikimedia.org/wikipedia/sco/3/3...,113
13,Charlton Athletic,https://upload.wikimedia.org/wikipedia/en/5/5b...,114
14,Chelsea FC,https://upload.wikimedia.org/wikipedia/en/c/cc...,115
15,Coventry City,https://upload.wikimedia.org/wikipedia/en/7/7b...,116
16,Crystal Palace,https://upload.wikimedia.org/wikipedia/en/a/a2...,117
17,Derby County,https://upload.wikimedia.org/wikipedia/en/4/4a...,118
18,Everton FC,https://upload.wikimedia.org/wikipedia/en/7/7c...,119
19,Fulham FC,https://upload.wikimedia.org/wikipedia/en/e/eb...,120
20,Huddersfield Town,https://upload.wikimedia.org/wikipedia/en/4/43...,121
21,Hull City,https://upload.wikimedia.org/wikipedia/en/5/54...,122
22,Ipswich Town,https://upload.wikimedia.org/wikipedia/en/4/43...,123
23,Leeds United,https://upload.wikimedia.org/wikipedia/en/5/54...,124
24,Leicester City,https://upload.wikimedia.org/wikipedia/en/2/2d...,125
25,Liverpool FC,https://upload.wikimedia.org/wikipedia/en/0/0c...,126
26,Luton Town,https://upload.wikimedia.org/wikipedia/en/9/9d...,127
27,Manchester City,https://upload.wikimedia.org/wikipedia/en/e/eb...,128
28,Manchester United,https://upload.wikimedia.org/wikipedia/en/7/7a...,129
29,Middlesbrough FC,https://upload.wikimedia.org/wikipedia/en/2/2c...,130
30,Newcastle United,https://upload.wikimedia.org/wikipedia/en/5/56...,131
31,Norwich City,https://upload.wikimedia.org/wikipedia/en/1/17...,132
32,Nottingham Forest,https://upload.wikimedia.org/wikipedia/en/e/e5...,133
33,Oldham Athletic,https://upload.wikimedia.org/wikipedia/en/a/a2...,134
34,Portsmouth FC,https://upload.wikimedia.org/wikipedia/en/3/3c...,135
35,Queens Park Rangers,https://upload.wikimedia.org/wikipedia/en/3/31...,136
36,Reading FC,https://upload.wikimedia.org/wikipedia/en/1/11...,137
37,Sheffield United,https://upload.wikimedia.org/wikipedia/en/9/9c...,138
38,Sheffield Wednesday,https://upload.wikimedia.org/wikipedia/en/a/a5...,139
39,Southampton FC,https://upload.wikimedia.org/wikipedia/en/c/c9...,140
40,Stoke City,https://upload.wikimedia.org/wikipedia/en/b/bf...,141
41,Sunderland AFC,https://upload.wikimedia.org/wikipedia/sco/7/7...,142
42,Swansea City,https://upload.wikimedia.org/wikipedia/sco/f/f...,143
43,Swindon Town,https://upload.wikimedia.org/wikipedia/en/a/a3...,144
44,Tottenham Hotspur,https://upload.wikimedia.org/wikipedia/en/b/b4...,145
45,Watford FC,https://upload.wikimedia.org/wikipedia/en/e/e2...,146
46,West Bromwich Albion,https://upload.wikimedia.org/wikipedia/en/8/8b...,147
47,West Ham United,https://upload.wikimedia.org/wikipedia/en/c/c2...,148
48,Wigan Athletic,https://upload.wikimedia.org/wikipedia/en/4/43...,149
49,Wimbledon FC (- 2004),https://upload.wikimedia.org/wikipedia/en/b/b3...,150
50,Wolverhampton Wanderers,https://upload.wikimedia.org/wikipedia/en/f/fc...,151

In [6]:
d_matches = pd.read_csv(r'..\data-csv\premier-matches.csv')

display(d_matches)

,season_id,round_id,match_id,home_team,final_score,away_team,date,referee,attendance
0,GB1-1992,R-1992-01,M-1992-01-001,Chelsea FC,1:1,Oldham Athletic,15/08/1992,Jim Borrett,20699
1,GB1-1992,R-1992-01,M-1992-01-002,Coventry City,2:1,Middlesbrough FC,15/08/1992,Howard King,12681
2,GB1-1992,R-1992-01,M-1992-01-003,Crystal Palace,3:3,Blackburn Rovers,15/08/1992,Roger Milford,17086
3,GB1-1992,R-1992-01,M-1992-01-004,Everton FC,1:1,Sheffield Wednesday,15/08/1992,Kelvin Morton,27687
4,GB1-1992,R-1992-01,M-1992-01-005,Ipswich Town,1:1,Aston Villa,15/08/1992,Alf Buksh,16818
...,...,...,...,...,...,...,...,...,...
13140,GB1-2025,R-2025-38,M-2025-38-006,Manchester City,1:2,Aston Villa,24/05/2026,Andrew Madley,60332
13141,GB1-2025,R-2025-38,M-2025-38-007,Nottingham Forest,1:1,AFC Bournemouth,24/05/2026,Craig Pawson,30741
13142,GB1-2025,R-2025-38,M-2025-38-008,Sunderland AFC,2:1,Chelsea FC,24/05/2026,Chris Kavanagh,47155
13143,GB1-2025,R-2025-38,M-2025-38-009,Tottenham Hotspur,1:0,Everton FC,24/05/2026,Michael Oliver,61812
13144,GB1-2025,R-2025-38,M-2025-38-010,West Ham United,3:0,Leeds United,24/05/2026,Anthony Taylor,62471

In [13]:
f_placements = pd.read_csv(r'..\data-csv\premier-placements.csv')

team_remade = pd.unique(f_placements['team_name'])
team_remade.sort()

df_team_remade = pd.DataFrame(team_remade)

display(f_placements)
# df_team_remade.to_csv('teams_test.csv')

,season_id,round_id,placement,team_name,matches,wins,draws,losses,goals,goal_dif,points
0,GB1-1992,R-1992-01,1,Norwich City,1,1,0,0,4:2,2,3
1,GB1-1992,R-1992-01,2,Coventry City,1,1,0,0,2:1,1,3
2,GB1-1992,R-1992-01,3,Leeds United,1,1,0,0,2:1,1,3
3,GB1-1992,R-1992-01,4,Sheffield United,1,1,0,0,2:1,1,3
4,GB1-1992,R-1992-01,5,Nottingham Forest,1,1,0,0,1:0,1,3
...,...,...,...,...,...,...,...,...,...,...,...
26327,GB1-2025,R-2025-38,16,Nottingham Forest,38,11,11,16,48:51,-3,44
26328,GB1-2025,R-2025-38,17,Tottenham Hotspur,38,10,11,17,48:57,-9,41
26329,GB1-2025,R-2025-38,18,West Ham United,38,10,9,19,46:65,-19,39
26330,GB1-2025,R-2025-38,19,Burnley FC,38,4,10,24,38:75,-37,22
26331,GB1-2025,R-2025-38,20,Wolverhampton Wanderers,38,3,11,24,27:68,-41,20